//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignStudioCoursework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int Attachment_ID { get; set; }
        public string Attachment_path { get; set; }
        public Nullable<int> Project_Ref { get; set; }
    
        public virtual Design_Project Design_Project { get; set; }
    }
}
