//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignStudioCoursework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Design_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Design_Project()
        {
            this.Attachment = new HashSet<Attachment>();
            this.Task = new HashSet<Task>();
        }
    
        public int Project_ID { get; set; }
        public string Project_name { get; set; }
        public Nullable<decimal> Project_price { get; set; }
        public Nullable<int> Employee_Ref { get; set; }
        public Nullable<int> Order_Ref { get; set; }
        public Nullable<int> Interior_type_Ref { get; set; }
        public Nullable<int> Style_Ref { get; set; }
        public Nullable<int> Project_status_Ref { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Interior_Type Interior_Type { get; set; }
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
        public virtual Style Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
